# Generated by Django 5.0 on 2024-04-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kinopoiskapp', '0005_rename_titl_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('age_category', models.CharField(choices=[('kids', 'Kids'), ('teen', 'Teen'), ('adult', 'Adult')], max_length=20)),
            ],
        ),
    ]
