# Generated by Django 5.0 on 2024-04-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kinopoiskapp', '0007_rename_price_item_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
